pull_request_rules:
  - name: automatic merging of greenkeeper pulls
    conditions:
      - author=greenkeeper[bot]
      - status-success=Travis CI - Pull Request
      - status-success=greenkeeper/verify
      - label!=WIP
    actions:
      merge:
        method: merge
        strict: true
  - name: delete merged branches
    conditions:
      - merged
    actions:
      delete_head_branch: {}
  - name: add WIP label when WIP is in title
    conditions:
      - title~=WIP
    actions:
      comment:
        message: Please remove WIP from the title. I have set the WIP Label for you instead.
      label:
        add:
          - WIP
