language: node_js
node_js:
  - lts/*
script:
  - npm run build
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo $TRAVIS_PULL_REQUEST_BRANCH; fi)
notifications:
  email: false
cache:
  directories:
    - node_modules
deploy:
  skip_cleanup: true
  provider: firebase
  on:
    branch: master